post_data = [
    {
        "id": 1,
        "title": "Introduction to Flask",
        "body": "Flask is a micro web framework written in Python.",
        "userId": 1,
        "dateCreated": "2024-01-10T12:30:45",
        "likes": 15,
    },
    {
        "id": 2,
        "title": "Building a RESTful API",
        "body": "Learn how to create a RESTful API with Flask and PostgreSQL.",
        "userId": 2,
        "dateCreated": "2024-01-11T09:15:20",
        "likes": 23,
    },
    {
        "id": 3,
        "title": "User Authentication Strategies",
        "body": "Explore token-based authentication and best practices.",
        "userId": 3,
        "dateCreated": "2024-01-12T15:40:10",
        "likes": 10,
    },
    {
        "id": 4,
        "title": "Advanced Database Queries",
        "body": "Optimizing queries for better performance.",
        "userId": 1,
        "dateCreated": "2024-01-13T11:55:30",
        "likes": 18,
    },
    {
        "id": 5,
        "title": "Deploying Flask Applications",
        "body": "Explore deployment options and best practices.",
        "userId": 2,
        "dateCreated": "2024-01-14T14:20:55",
        "likes": 30,
    },
    {
        "id": 6,
        "title": "Error Handling Strategies",
        "body": "Implementing effective error handling in Flask applications.",
        "userId": 3,
        "dateCreated": "2024-01-15T10:10:05",
        "likes": 12,
    },
    {
        "id": 7,
        "title": "Testing Flask Applications",
        "body": "Writing unit tests for Flask routes and handlers.",
        "userId": 1,
        "dateCreated": "2024-01-16T13:45:40",
        "likes": 25,
    },
    {
        "id": 8,
        "title": "Scaling Flask Applications",
        "body": "Strategies for scaling Flask applications to handle more traffic.",
        "userId": 2,
        "dateCreated": "2024-01-17T08:25:15",
        "likes": 21,
    },
    {
        "id": 9,
        "title": "Building a Chat Application",
        "body": "Creating a real-time chat application using Flask-SocketIO.",
        "userId": 3,
        "dateCreated": "2024-01-18T16:00:00",
        "likes": 17,
    },
    {
        "id": 10,
        "title": "Introduction to GraphQL with Flask",
        "body": "Learn the basics of GraphQL and integrate it into your Flask applications.",
        "userId": 1,
        "dateCreated": "2024-01-19T12:12:12",
        "likes": 28,
    }
]